---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      description: Retrieves all users
      responses:
        '200':
          description: successful
  



    post:
      summary: create user
      tags:
      - Users
      description: Creates a user
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password_digest
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      description: Shows a user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      tags:
      - Users
      description: Updates a user
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password_digest
    put:
      summary: update user
      tags:
      - Users
      description: Updates a user
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password_digest
    delete:
      summary: delete user
      tags:
      - Users
      description: Deletes a user
      responses:
        '200':
          description: successful
servers:
- url: http://[::1]:3000
  variables:
    defaultHost:
      default: http://[::1]:3000
